version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - calc-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - calc-network

networks:
  calc-network:
    driver: bridge
